name = "cloud-switch-site"
compatibility_date = "2024-09-23"

# Serve static assets from ./public
[assets]
directory = "./public"

# Custom domains (creates DNS records automatically)
[[routes]]
pattern = "kill-switch.net"
custom_domain = true

[[routes]]
pattern = "www.kill-switch.net"
custom_domain = true
